# Generated by Django 4.2.3 on 2023-07-31 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevator_id', models.IntegerField()),
                ('current_floor', models.IntegerField()),
                ('operational', models.BooleanField(default=True)),
                ('direction', models.CharField(choices=[('Up', 'Up'), ('Down', 'Down'), ('Idle', 'Idle')], default='Idle', max_length=10)),
                ('is_busy', models.BooleanField(default=False)),
                ('door', models.CharField(choices=[('Close', 'Close'), ('Open', 'Open')], default='Close', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requesting_floor', models.IntegerField()),
                ('destination_floor', models.IntegerField(null=True)),
                ('elevator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.elevator')),
            ],
        ),
    ]
